### ISSUE TITLE
use ticker api for calculating assets

### ISSUE THREAD

**Issue by c9s** [c9s/bbgo#100]

**Comment by ychi** [comment]
Use ticker in [here](https://github.com/c9s/bbgo/blob/main/pkg/cmd/pnl.go#L93), and `lastPrice`(binance) `last`(MAX) is equivalent to the `close` of current kline?

**Comment by ychi** [comment]
[ListPriceChangeStatsService](https://github.com/adshao/go-binance/blob/master/v2/ticker_service.go#L106) looks helpful

**Comment by c9s** [comment]
yeah, and in the environment.go file, we are currently using kline to get the latest price of each market.

**Comment by ychi** [comment]
> yeah, and in the environment.go file, we are currently using kline to get the latest price of each market.
`ExchangeSession.LastPrice()`?

Just found `GET /api/v3/ticker/price` on binance, the rate limit weight is 1 for a single symbol, 2 when symbol parameter is omitted. But the return value only contain last price. (24hr ticker weights 1 for a single symbol, but 40 if not specifying symbol.)

I think it's okay to use binance 24hr ticker? It returns more info, more similar to Max ticker response. Just make sure `types.Exchange.QueryTicker()` always require a symbol.

**Comment by c9s** [comment]
sounds good! let’s do it

ychi <notifications@github.com>於 2021年2月4日 週四，06:34寫道：

**Comment by c9s** [comment]
done, thanks @ychi

**Comment by ychi** [comment]
Sorry I just got MetaMask setup 😂
My account is `0xa2874B558459706865b2E1e4026560D59fc00dE2` if it's not too late for receiving BBG

**Comment by c9s** [comment]
it’s on the way!
