### ISSUE TITLE
switch binance /fapi/v1/account to /fapi/v2/account

### ISSUE THREAD

**Issue by b1u3h4t** [c9s/bbgo#1292]
https://binance-docs.github.io/apidocs/futures/en/#change-log
The following endpoints will no longer be supported from 2023-07-15:
GET /fapi/v1/account
Please switch to corresponding v2 endpoints:
GET /fapi/v2/account

go-binance upgrade futures account service to v2 version: 
https://github.com/adshao/go-binance/commit/e728846b51573447ffa75698e236e712ce81725b
https://github.com/adshao/go-binance/commit/f03d80e1dd4308c4a35d3ef4eda9340134228b00

**Comment by playniuniu** [comment]
same problem, need update go-binance package to support new api, else the futures trading will be error.

**Comment by c9s** [comment]
there is a PR for this #1306
