### ISSUE TITLE
Feature: Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by kalyani2003** [c9s/bbgo#1469]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/c9s/bbgo/assets/84217977/04271c27-42df-450a-879a-6bf141d7e445)

**Comment by kalyani2003** [comment]
@c9s  Kindly assign me this issue, I want to work on it. Thank You.

**Comment by zenixls2** [comment]
I would prefer developers to go to the insights tab and check the contributors on their own.
try to take more time in writing useful documentation if you really want to contribute to the project.

**Comment by kalyani2003** [comment]
Yeah, Sure!

**Comment by zenixls2** [comment]
looks like you're sending same issues everywhere.
since this is not our top priority, I'm going to close the issue. 
please contribute more to the documentation.
