### ISSUE TITLE
common strategy is no initialised for some strategies

### ISSUE THREAD

**Issue by michaljirman** [c9s/bbgo#1518]
Just tried some other strategies e.g rsicross and emacross. Both of them fails to start a backtest. Does it work for anyone here, please? 

Step to reproduce:
`go run ./cmd/bbgo backtest -v --sync --config config/rsicross.yaml`

Panic log:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x101286ed0]

goroutine 1 [running]:
github.com/c9s/bbgo/pkg/strategy/common.(*Strategy).Initialize(0x14000ac20b8?, {0x101ec8080?, 0x14000146b90?}, 0x140000fb500, 0x1400066c000, {{0x14000a78387, 0x7}, {0x14000a78390, 0x7}, 0x8, ...}, ...)
 /Users/m/Documents/Dev/bbgo/pkg/strategy/common/strategy.go:41 +0x40
....
```

It seems to me that the issue is the Initialize() function of the strategy is not called to setup the common.Strategy.

**Comment by c9s** [comment]
should be fixed in v1.56.1
