### ISSUE TITLE
feature request: 讓各個 strategy 只能使用各自部分的資產

### ISSUE THREAD

**Issue by LarryLuTW** [c9s/bbgo#159]
## feature 描述

譬如說我總共有 5 個 strategy，而現有總資產十萬

希望有個方法可以設定讓資產平分成五分（兩萬），而每個 strategy 在執行時最多就是用自己那兩萬，即便現在其他 strategy 有閒置沒有到的資產，也不可以去動它

換句話說，即便是虧損，一個 strategy 最多也是把自己的部分虧完，不會因為 strategy 設定得不好而把全部的資產虧光

## 需要做的事

- 每個 strategy instance 有自己的餘額，下單之後要預扣餘額
- 如果單消化一半 也要把餘額更新 （quote and base)
- 如果取消單也要把餘額還回來
- 成交的話也要再把餘額扣除手續費

**Comment by c9s** [comment]
現在像 ftx, binance 應該都可以用子帳戶了, max 的話可以另外開帳號，只要 kyc 就可以了。

如果底層要做這個會導致架構太複雜，所以先不考慮喔~
