### ISSUE TITLE
db: Losing type information at creating other klines tables in SQLite

### ISSUE THREAD

**Issue by beckxie** [c9s/bbgo#202]
## Environment
  - branch: main
  - commit: 24a1205

## Description

I want to backtest by `SQLite`.
```
./bbgo backtest --exchange max --config config/bbgo.yaml -v --sync --sync-only --sync-from "2021-04-20"
```
And I got an Error: `Error: sql: Scan error on column index 0, name "gid": converting NULL to uint64 is unsupported`

### Full log
```
[0000]  INFO loaded max server timestamp: 1618934400 offset=-1 exchange=max
[0000]  INFO starting synchronization...
[0000]  INFO synchronizing lastKLine for interval 4h from exchange max
[0000]  INFO querying last kline exchange = max AND symbol = BTCTWD AND interval = 4h
[0000]  INFO querying kline BTCTWD 4h {Limit:1000 StartTime:2021-04-20 00:00:00 +0000 UTC EndTime:<nil>} exchange=max
[0000]  INFO synchronizing lastKLine for interval 12h from exchange max
[0000]  INFO querying last kline exchange = max AND symbol = BTCTWD AND interval = 12h
Error: sql: Scan error on column index 0, name "gid": converting NULL to uint64 is unsupported
[0000] FATAL cannot execute command error=sql: Scan error on column index 0, name "gid": converting NULL to uint64 is unsupported
```

## Problem

I figured out that schema type information was lost at creating other `klines` tables in SQLite.

## Expected Behavior

```
sqlite> .schema max_klines
CREATE TABLE `max_klines`
(
    `gid`           INTEGER PRIMARY KEY AUTOINCREMENT,
    `exchange`      VARCHAR(10)             NOT NULL,
    `start_time`    DATETIME(3)             NOT NULL,
    `end_time`      DATETIME(3)             NOT NULL,
    `interval`      VARCHAR(3)              NOT NULL,
    `symbol`        VARCHAR(7)              NOT NULL,
    `open`          DECIMAL(16, 8)  NOT NULL,
    `high`          DECIMAL(16, 8)  NOT NULL,
    `low`           DECIMAL(16, 8)  NOT NULL,
    `close`         DECIMAL(16, 8)  NOT NULL DEFAULT 0.0,
    `volume`        DECIMAL(16, 8)  NOT NULL DEFAULT 0.0,
    `closed`        BOOLEAN         NOT NULL DEFAULT TRUE,
    `last_trade_id` INT             NOT NULL DEFAULT 0,
    `num_trades`    INT             NOT NULL DEFAULT 0
);
```

## Actual Behavior

```
sqlite> .schema max_klines
CREATE TABLE max_klines(
  gid INT,
  exchange TEXT,
  start_time NUM,
  end_time NUM,
  interval TEXT,
  symbol TEXT,
  open NUM,
  high NUM,
  low NUM,
  close NUM,
  volume NUM,
  closed NUM,
  last_trade_id INT,
  num_trades INT
);
```

## Steps to Reproduce the Problem

  1. edit `env.local`
```
DB_DRIVER=sqlite3
DB_DSN=bbgo.sqlite3
```
  1. go build using `CGO_ENABLED=1`.
  1. `./bbgo backtest --exchange max --config config/bbgo.yaml -v --sync --sync-only --sync-from "2021-04-20"`
  1. `./bbgo backtest --exchange max --config config/bbgo.yaml -v --sync --sync-only --sync-from "2021-04-21"`
  > Noted: You need to sync twice if your SQLite file does not exist and the second sync will get an Error: `Error: sql: Scan error on column index 0, name "gid": converting NULL to uint64 is unsupported`.

**Comment by c9s** [comment]
Before I fix this issue, you may try the mysql driver.

**Comment by beckxie** [comment]
@c9s Yes, I already using MySQL now.

There are what I figure out :

https://stackoverflow.com/questions/12730390/copy-table-structure-to-new-table-in-sqlite3/12753695#comment41713137_12753695

And I'm not sure how to fit in `migrations`.

https://github.com/c9s/bbgo/blob/24a12050378af565e25845451af978757c513bce/migrations/sqlite3/20201106114742_klines.sql#L26-L36

https://github.com/c9s/bbgo/blob/24a12050378af565e25845451af978757c513bce/pkg/migrations/sqlite3/20201106114742_klines.go#L27-L40

**Comment by c9s** [comment]
you need to change the .sql file, and then compile the .sql files into .go file via the command `make migrations`, so that the tool generates the embedded migration package for you.

**Comment by zenixls2** [comment]
I believe this issue has been resolved (not facing this issue anymore in the recent releases)
close the issue.
