### ISSUE TITLE
feature: add grpc strategy(?)

### ISSUE THREAD

**Issue by narumiruna** [c9s/bbgo#214]
想要用 python 的 machine learning model 做交易

- 丟 klines, balances, orderbook ... 給 python 的 machine learning model 做預測
- 用 python 丟買賣的訊號給 bbgo

**Comment by c9s** [comment]
好啊

**Comment by c9s** [comment]
所以會有 long, hold, short 三種 signal 嗎

**Comment by c9s** [comment]
我有在想能夠做一種 signal strategy 他專門聽其他策略傳來的訊號來執行交易

**Comment by c9s** [comment]
grpc 可以是一種 signal backend

**Comment by narumiruna** [comment]
> 所以會有 long, hold, short 三種 signal 嗎

嗯嗯
long, hold, short 分別對應到不同的 symbol 和 quantity

**Comment by c9s** [comment]
balances 和 open orders 的資料可以透過 grpc service 開放出來（現在有 http api) 參考類似的方式就可以了

なるみ ***@***.***>於 2021年5月7日 週五，16:58寫道：
