### ISSUE TITLE
go-sqlite3 not work.

### ISSUE THREAD

**Issue by SDpower** [c9s/bbgo#222]
[With example step](https://github.com/c9s/bbgo#install-from-binary)
<img width="925" alt="圖片" src="https://user-images.githubusercontent.com/745625/117567237-e6bfcf80-b0ed-11eb-983a-f6aebe418545.png">

**Comment by c9s** [comment]
Hi @SDpower, I added the instruction in the readme (in this commit 0b7a83a)

**Comment by SDpower** [comment]
Hi @c9s  in my case is direct download from release it should be on you Makefile isn't.

**Comment by c9s** [comment]
doc is updated, added the missing instruction

https://github.com/c9s/bbgo/blob/main/doc/build-from-source.md
