### ISSUE TITLE
Can i work with marginFraction of FTX futures

### ISSUE THREAD

**Issue by lordvalium** [c9s/bbgo#267]
Hi 
i would like to create some strategy of marginFraction for FTX futures. 

Is that possible with that project?

**Comment by c9s** [comment]
@lordvalium Sure~

**Comment by c9s** [comment]
@lordvalium you can add a FuturesExchange interface to support Futures. that way, Binance Futures can also be supported.

**Comment by lordvalium** [comment]
I have connected FTX via api, but i need some logic for the fraction

**Comment by zenixls2** [comment]
FTX is fucked up by SBF. Close the issue.
