### ISSUE TITLE
Unable to connect with mysql

### ISSUE THREAD

**Issue by arthurwolf** [c9s/bbgo#279]
How do I connect with Mysql? 

The example config is:

DB_DSN=root@tcp(127.0.0.1:3306)/bbgo

So no password specified. So I have set things up in mysql using auth_socket, so no password is required.
If I just run the "mysql" command with no parameters, it just connects.

But if I run bbgo, it complains:

[0000]  INFO starting backtest with startTime Thu Oct  1 00:00:00 2020
Error: Error 1698: Access denied for user 'root'@'localhost'
[0000] FATAL cannot execute command error=Error 1698: Access denied for user 'root'@'localhost'

What am I doing wrong ??

**Comment by arthurwolf** [comment]
Follow-up: switching to password auth and doing:

DB_DSN=root:password@tcp(127.0.0.1:3306)/bbgo

did work. Do you want a PR so I add information about using mysql passwords to the Readme?

**Comment by c9s** [comment]
@arthurwolf thanks! someone just updated the readme yesterday!

closing this one, since the readme is updated.
