### ISSUE TITLE
Frontend instructions not working

### ISSUE THREAD

**Issue by arthurwolf** [c9s/bbgo#280]
Hello.

Trying to get the frontend running, following the instructions given in the Readme do not work:

arthur@crypto:~/bbgo$ cd github/bbgo/frontend/
arthur@crypto:~/bbgo/github/bbgo/frontend$ ls
README.md  api  components  layouts  next-env.d.ts  next.config.js  node_modules  package-lock.json  package.json  pages  postcss.config.js  public  src  styles  tsconfig.json
arthur@crypto:~/bbgo/github/bbgo/frontend$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

What am I doing wrong? Is there some additional command or pre-requesite I am missing?

Thank you!

**Comment by arthurwolf** [comment]
@austin362667 on telegram says to use --enable-webserver to get the frontend, but I'm not sure exactly what this means.
Passing it to bbgo causes an error:

arthur@crypto:~/bbgo$ ./bbgo --enable-webserver
Error: unknown flag: --enable-webserver
[0000] FATAL cannot execute command error=unknown flag: --enable-webserver

If it's about passing it while building bbgo, I wasn't able to build bbgo when I followed the instructions (the "go" commands just did nothing)

**Comment by arthurwolf** [comment]
For note taking, instructions from the telegram channel:

![Screenshot from 2021-11-29 11-59-13](https://user-images.githubusercontent.com/108821/143856149-5ebfb4c9-e1ea-4089-a9a6-0e8fe236fb86.png)

**Comment by c9s** [comment]
`yarn install` should work or you don't have `yarn` installed?


try:
```
npm install --global yarn
```

**Comment by c9s** [comment]
checked, it should be:

`./bbgo run --enable-webserver`

The `--enable-webserver` option is only for the `run` command.

**Comment by c9s** [comment]
updated readme in e5da4e44

thank you for reporting this~
