### ISSUE TITLE
Missing information on options

### ISSUE THREAD

**Issue by arthurwolf** [c9s/bbgo#281]
hello. I'm having trouble getting this to work, in particular I don't know what some of the configuration variables mean. 

is the github readme all the documentation there is? is there some website I am missing? 

what is grid/profitSpread? 
what is grid/long? 
I can imagine what scaleQuantity does (non-linear grid pattern?), but what do the different options mean/do ?

**Comment by c9s** [comment]
the profit spread is, when your buy order is executed, what's the profit price spread that you want to add to your sell order. for example, you have a buy order with price 100 and which is executed, then if your profit spread is 5, your sell order to be submitted will sell at 105.

`long` means when your buy order is executed at price 100 * quantity 1 (amount = $100), if your profit spread is 5, you will sell it at 105 with the same amount ($100), the quantity for sell will be (100 / 105 = 0.952). This way you will keep 0.048 quantity in your spot wallet.


We can add the doc for that, thanks for reporting!

**Comment by andycheng123** [comment]
@c9s I'll add this to the doc when I add docs about support strategy

**Comment by c9s** [comment]
doc added
