### ISSUE TITLE
bbgo pnl is not working

### ISSUE THREAD

**Issue by tony1223** [c9s/bbgo#287]
The document says  there's a command like this:
bbgo pnl --exchange binance --asset BTC --since "2019-01-01"

but it shows 
`
 FATAL cannot execute command error=unknown flag: --exchange
`

if i try
`bbgo pnl --session binance --symbol BTC`

it shows
`[0000] FATAL cannot execute command error=market config BTC not found`

Not sure which input should be the right one. @_@

**Comment by c9s** [comment]
symbol should be something like `BTCUSDT`

**Comment by tony1223** [comment]
go run .\cmd\bbgo\main.go pnl --session ftxStable --symbol XRPUSDT 
[0000]  INFO syncing symbols [] from session ftxStable
Error: market config XRPUSDT not found
[0000] FATAL cannot execute command error=market config XRPUSDT not found
exit status 1

**Comment by c9s** [comment]
@tony1223 這個應該是 symbol 沒有 convert
