### ISSUE TITLE
Installing from source.

### ISSUE THREAD

**Issue by arthurwolf** [c9s/bbgo#289]
Since the latest release doesn't have the fix for the « fatal error: concurrent map read and map write » error discussed previously; I need to use bbgo from source.

The documentation says to do:

`go get -u github.com/c9s/bbgo/cmd/bbgo`

But if I do that, I get:

```
arthur@crypto:~/bbgo/goget$ go get -u github.com/c9s/bbgo/cmd/bbgo
package github.com/hashicorp/hcl/hcl/printer: cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
        /usr/lib/go-1.13/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
        /home/arthur/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)
```

And then nothing. No new files, no new commands installed, nothing.

What am I doing wrong?

**Comment by tony1223** [comment]
You could try another way. 

(the following instruction works in linux. )
1. install go and setup gopath
2. install make
3. type ```make bbgo-slim``` in the project root, then the binary will build to  **build/bbgo/** folder.
(If you need the web function,you have to install yarn or more items and **make bbgo **

**Comment by arthurwolf** [comment]
I am not familiar at all with go/gopath, how exactly would you do step 1, like precise commands? (@tony1223 )

**Comment by c9s** [comment]
doc updated in https://github.com/c9s/bbgo/blob/main/doc/build-from-source.md
