### ISSUE TITLE
add a paramter for skip backtest confirm

### ISSUE THREAD

**Issue by tony1223** [c9s/bbgo#294]
Everytime we will be asked about the backtest for the database isolation confirm,
it's really annoying for those user who already separate the config/database. 

Providing a command argument "force" to skip this.

**Comment by arthurwolf** [comment]
Until this is fixed, you can use the "expect" command if you are using linux. Here is the script I use:

```
arthur@crypto:~/bbgo$ cat do-backtest.sh 
#!/usr/bin/expect -f
set timeout -1
spawn ./bbgo backtest --exchange [lindex $argv 0] --config [lindex $argv 1] -v --base-asset-baseline
expect "Are you sure to continue"
send "y\n\r"
expect eof
#expect "DATA PERFORMANCE"
```

**Comment by tony1223** [comment]
> Until this is fixed, you can use the "expect" command if you are using linux. Here is the script I use:
> 
> ```
> arthur@crypto:~/bbgo$ cat do-backtest.sh 
> #!/usr/bin/expect -f
> set timeout -1
> spawn ./bbgo backtest --exchange [lindex $argv 0] --config [lindex $argv 1] -v --base-asset-baseline
> expect "Are you sure to continue"
> send "y\n\r"
> expect eof
> #expect "DATA PERFORMANCE"
> ```

Thanks, it's a bit too complicated for the lazy me,haha.
I have submited a PR for the maintainer. cc

**Comment by tony1223** [comment]
Since the PR got merged so I am going to close the comment.
