### ISSUE TITLE
Release v1.18.1 has a new error.

### ISSUE THREAD

**Issue by arthurwolf** [c9s/bbgo#301]
I get the following error when running a backfill with 1.18.1, even though this worked perfectly with 1.18.0 just before:

![Screenshot from 2021-12-04 20-50-20](https://user-images.githubusercontent.com/108821/144722815-e1cea368-8263-4e6e-84c8-8f8608ce39df.png)

Note: I removed and created the mysql database from scratch for this, just to be sure.

**Comment by c9s** [comment]
this is fixed, thanks for reporting!
