### ISSUE TITLE
Binance Futures

### ISSUE THREAD

**Issue by MikeCoderr** [c9s/bbgo#422]
Dear Team,

I would be greatly interested to have the functionality of binance futures, and then maybe later other futures.

Is that anywhere on your roadmap? 

thanks
Mike

**Comment by c9s** [comment]
yes, @austin362667 and I are working on the Binance futures support, do you want to join the development?

**Comment by MikeCoderr** [comment]
I am a seasoned c# coder, though I am trying my step with GO for now.. so not sure what you see fit for me at the moment?

**Comment by c9s** [comment]
@MikeCoderr help us test it?

**Comment by c9s** [comment]
you can join our telegram channel https://t.me/bbgo_intl

**Comment by MikeCoderr** [comment]
I look into it for sure!

**Comment by c9s** [comment]
it's done and so we are closing this one
