### ISSUE TITLE
replace the current decimal system

### ISSUE THREAD

**Issue by c9s** [c9s/bbgo#439]

**Comment by arthurwolf** [comment]
The main issue with this is performance.
@c9s mentionned it's possible this could have a huge cost in terms of computing power. I'm surprised a modern CPU with all the FP instructions would have issues with this, but I'm not very knoweledgable on this/what is available in Go. Maybe some of the most computationally expensive tasks could be implemented in C/C++ as a separate module? If you can define clearly what the module must do, I could potentially pay somebody to code it?

**Comment by zenixls2** [comment]
suspect the high CPU loading is caused by fixedpoint::Parse function.  
if possible, please provide me a way to cause heavy CPU loading.

**Comment by zenixls2** [comment]
maybe able to close? @c9s

**Comment by c9s** [comment]
@zenixls2   yes, it's done, thanks for your effort!
