### ISSUE TITLE
kline cmd not work?! 

### ISSUE THREAD

**Issue by SDpower** [c9s/bbgo#448]
Look line this cmd provide a Stream to get public data.
As comment show have an **exchange** "--exchange=ftx"
https://github.com/c9s/bbgo/blob/main/pkg/cmd/kline.go#L16

now:
```
 $ go run ./cmd/bbgo kline --exchange=binance --symbol=BTCUSDT
Error: unknown flag: --exchange
[0000] FATAL cannot execute command error=unknown flag: --exchange
exit status 1
 $ go run ./cmd/bbgo kline --symbol=BTCUSDT
[0000]  INFO loaded max server timestamp: 1643999878 offset=0 exchange=max
Error: session  not found
[0000] FATAL cannot execute command error=session  not found
exit status 1
```

**Comment by zenixls2** [comment]
You have to remove max settings from your config, or add the max key to your dotenv

**Comment by SDpower** [comment]
I don't have any config.
Before version without any config will work this was i expect. 
If not sure provide an "minimal.yaml" how to work and remove Line 16 and 87.
