### ISSUE TITLE
Segmentation violation when running flashcrash in backtest mode

### ISSUE THREAD

**Issue by vinceyap88** [c9s/bbgo#477]
Hi,
   I have encountered the below error after adding the backtest section in the flashcrash.yaml.
================
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe81d2f]
================
   Further details can be found in the attached log.

[flashcrash.log](https://github.com/c9s/bbgo/files/8246297/flashcrash.log)
[flashcrash.xml.txt](https://github.com/c9s/bbgo/files/8246303/flashcrash.xml.txt)

  Command to run:
source .env.local && go run ./cmd/bbgo backtest -v  --base-asset-baseline --config config/myflashcrash.yaml

**Comment by c9s** [comment]
@vinceyap88 Hi, we are checking it.
