### ISSUE TITLE
Unstopped buy orders in backtest of the flashcrash strategy

### ISSUE THREAD

**Issue by vinceyap88** [c9s/bbgo#482]
The balance is set to 300 usdt, but the buy orders are created without stop during backtest.

[myflashcrash.log](https://github.com/c9s/bbgo/files/8254367/myflashcrash.log)
[myflashcrash.yaml.txt](https://github.com/c9s/bbgo/files/8254370/myflashcrash.yaml.txt)

**Comment by zenixls2** [comment]
actually it's correct. Just that it doesn't output the cancel order log in between.

**Comment by zenixls2** [comment]
there's an improvement in #485
