### ISSUE TITLE
Install via git clone - step fail in "yarn install"

### ISSUE THREAD

**Issue by vinceyap88** [c9s/bbgo#483]
> cd frontend && yarn install
> 00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

**Comment by c9s** [comment]
can you show where is your yarn? maybe you're calling a different `yarn`

![image](https://user-images.githubusercontent.com/50894/160052179-539e8960-1312-44e0-ae8c-f24927e54ec7.png)

**Comment by vinceyap88** [comment]
oh, not this yarn ah.

<img width="483" alt="Screenshot 2022-04-02 at 5 20 50 PM" src="https://user-images.githubusercontent.com/12798134/161376664-1478679a-d10d-443a-a8ca-effd4b245c40.png">

**Comment by c9s** [comment]
yeah, please install the js yarn
