### ISSUE TITLE
No response after entering /auth and token in Telegram Bot

### ISSUE THREAD

**Issue by vinceyap88** [c9s/bbgo#534]
Hi,
   I have followed the steps(attached) to use the telegram bot, but there are no response after enter the /auth and token.

The log showed:
time="2022-04-16T22:10:21+08:00" level=info msg="[telegram] allocated a new session: &{BaseSession:{OriginState:public CurrentState:public Authorized:false StartedTime:2022-04-16 22:10:21.437707967 +0800 +08 m=+29.895387138 authorizing:false} telegram:0xc00098ab40 User:0xc000b0e910 Chat:0xc000b0a700}"
time="2022-04-16T22:10:21+08:00" level=info msg="[interact] transiting state from public -> /auth_0"
time="2022-04-16T22:10:21+08:00" level=info msg="[interact] transiting state from /auth_0 -> /auth_1"
time="2022-04-16T22:10:40+08:00" level=info msg="[telegram] onText: &{ID:60 InlineID: Sender:0xc000b0e960 Unixtime:1650118239 Chat:0xc000b0a7e0 SenderChat:<nil> OriginalSender:<nil> OriginalChat:<nil> OriginalMessageID:0 OriginalSignature: OriginalSenderName: OriginalUnixtime:0 ReplyTo:<nil> Via:<nil> LastEdit:0 AlbumID: Signature: Text:" .........
.
.
time="2022-04-16T22:10:40+08:00" level=info msg="[telegram] loaded existing session: &{BaseSession:{OriginState:public CurrentState:/auth_1 Authorized:false StartedTime:2022-04-16 22:10:21.437707967 +0800 +08 m=+29.895387138 authorizing:false} telegram:0xc00098ab40 User:0xc000b0e910 Chat:0xc000b0a700}"
time="2022-04-16T22:10:40+08:00" level=warning msg="[telegram] telegram is set to private mode, skipping message"

![telegram-cloud-photo-size-5-6255752018928971803-y](https://user-images.githubusercontent.com/12798134/163678930-a8229c10-47f1-499c-9b82-8299b6d6cf20.jpg)

**Comment by c9s** [comment]
this is resolved
