### ISSUE TITLE
Backtesting error: dublicate orders in report

### ISSUE THREAD

**Issue by ksidenko** [c9s/bbgo#673]
I run custom experimental strategy DCA and have dublicates orders in chart.

UI
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/8588439/172058087-329ea068-7396-49b4-89f7-bf1e762872c0.png">

orders.tsv
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/8588439/172058074-05163b45-e599-4871-9ddd-66608d2e7e0c.png">

**Comment by c9s** [comment]
thanks! looks the order update triggered twice, i will fix it

**Comment by c9s** [comment]
@ksidenko would you mind submitting the DCA strategy as a PR, so I can reproduce it?

Just to verify, did you use go routine in your strategy?

**Comment by c9s** [comment]
which order type do you use in your strategy? market order or limit order?

**Comment by ksidenko** [comment]
Market order

**Comment by ksidenko** [comment]
Its very simple strategy, just buy fixed amount of symbol by **market** every N days. No go routings.
I made logging from stream
`session.UserDataStream.OnOrderUpdate(...)`

And reproduce duplicate error
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/8588439/172077028-0ff176f3-9e61-4c4c-a9a0-b394f64b6f69.png">

**Comment by c9s** [comment]
fixed

**Comment by ksidenko** [comment]
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/8588439/172669172-a56e629b-be8d-43a6-9322-0b4b988b2185.png">
Dubicateles in orders was removed! Greate!

Some minor issue stays: dublicates messages in logs 
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/8588439/172669464-6437aa15-daed-4f46-912a-bed2f4eefa22.png">

**Comment by c9s** [comment]
@ksidenko the other log is from the core, so it's the same object~

**Comment by c9s** [comment]
@ksidenko btw, dca strategy is added, you can check the config/dca.yaml

**Comment by ksidenko** [comment]
sorry, dubles of logs in console - my error, copy / paste ((
