### ISSUE TITLE
ERROR submit order error error=unexpected end of JSON input

### ISSUE THREAD

**Issue by jwmdev** [c9s/bbgo#985]
I am trying inbuilt swing strategy but  I am getting an error when order is submitted. The error says: ERROR submit order error error=unexpected end of JSON input.

What might be the issue?

**Comment by c9s** [comment]
the swing strategy is now deprecated, so maybe you need to retry other strategy.

which crypto exchange do you use?

**Comment by jwmdev** [comment]
> the swing strategy is now deprecated, so maybe you need to retry other strategy.
> 
> which crypto exchange do you use?

Kucoin

**Comment by c9s** [comment]
closing this. thanks
