### ISSUE TITLE
FTX API Optimized access support

### ISSUE THREAD

**Issue by hththt** [c9s/bbgo#998]
Make a wish, FTX API Optimized access support :D

ref: https://ftx.com/settings/api

Whitelisted  IPs optimized that it never leaves AWS: it does not go through Cloudflare

REST API users should use a different endpoint base url for your get, place, and cancel order requests: https://api.ftx.com. 
Below are the endpoints that are usable. We intend on adding more over time:
Place order: POST /orders
Cancel order:
By order ID: DELETE /orders/[id]
By client order ID: DELETE /orders/by_client_id/[id]
Get open orders: GET /orders
Get fills: GET /fills
Get balances: GET /wallet/balan

**Comment by austin362667** [comment]
Hi, there. We've surveyed this tech yesterday: Optimized Access via FTX.
Sadly, no tremendous latency breakthroughs were found. Even slower than binance which both from AWS Tokyo-1A
Below is our latency statistics screenshot from FTX:
![image](https://user-images.githubusercontent.com/35886692/198328344-d8412791-de54-4110-b894-379e9dbffede.png)

**Comment by austin362667** [comment]
@hththt  May I ask why you are requesting this feature? Are you doing some HFT stuff?

**Comment by hththt** [comment]
hmmm, seems that 'optimized access ' not makeing too much difference :p
im not doing HFT right now, just new arrival and learning bbgo actually
whatever, this is a excellent project, got so much fun from it. many thanks

**Comment by zenixls2** [comment]
Close the issue since FTX is messed up by SBF.
