### ISSUE TITLE
Request Triangle Arbitrage Multicycle Example

### ISSUE THREAD

**Issue by zhihuba** [c9s/bbgo#999]
It's a good project and I checked the documentation. Can be used to make portfolios, and custom cycles. But how to implement a strategy similar to the triangle arbitrage. or handle both 1-hour and 4-hour candles in one strategy

**Comment by c9s** [comment]
you can implement it via the CrossExchangeStrategy interface, implement CrossRun() and CrossSubscribe()

take a look at xmaker or xnav, it's a standard example of implementing a cross exchange strategy

**Comment by c9s** [comment]
I will close this one. there are already some users implemented their own arb strategy as a private strategy. It's not hard to implement one. ;-)
